--- #This is my loops playbook
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh
  tasks:
          - name: creating multiple users
            user: name='{{item}}' state=present
            with_items:
                   - Varunan
                   - Thulir
                   - Gowtham
                   - Nirai
                   - Vel

